// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WEBNC.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220032004_AllowNullIdDonDatInDanhGia")]
    partial class AllowNullIdDonDatInDanhGia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietDonHang", b =>
                {
                    b.Property<string>("idDonDat")
                        .HasColumnType("char(5)");

                    b.Property<string>("idSanPham")
                        .HasColumnType("char(5)");

                    b.Property<decimal>("donGia")
                        .HasColumnType("money");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.HasKey("idDonDat", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietDonHang");

                    b.HasData(
                        new
                        {
                            idDonDat = "DH001",
                            idSanPham = "SP01",
                            donGia = 4500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH001",
                            idSanPham = "SP08",
                            donGia = 1200000m,
                            soluong = 2
                        },
                        new
                        {
                            idDonDat = "DH002",
                            idSanPham = "SP03",
                            donGia = 5200000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH002",
                            idSanPham = "SP05",
                            donGia = 3500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH003",
                            idSanPham = "SP14",
                            donGia = 8500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH004",
                            idSanPham = "SP02",
                            donGia = 9500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH004",
                            idSanPham = "SP06",
                            donGia = 3800000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH005",
                            idSanPham = "SP15",
                            donGia = 13500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH005",
                            idSanPham = "SP10",
                            donGia = 3100000m,
                            soluong = 2
                        },
                        new
                        {
                            idDonDat = "DH006",
                            idSanPham = "SP17",
                            donGia = 1500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH007",
                            idSanPham = "SP11",
                            donGia = 1100000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH007",
                            idSanPham = "SP19",
                            donGia = 1800000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH008",
                            idSanPham = "SP04",
                            donGia = 8700000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH008",
                            idSanPham = "SP07",
                            donGia = 4200000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH009",
                            idSanPham = "SP12",
                            donGia = 2300000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH009",
                            idSanPham = "SP22",
                            donGia = 3400000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH010",
                            idSanPham = "SP13",
                            donGia = 1800000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH011",
                            idSanPham = "SP16",
                            donGia = 18500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH012",
                            idSanPham = "SP18",
                            donGia = 2800000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH013",
                            idSanPham = "SP20",
                            donGia = 2200000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH014",
                            idSanPham = "SP21",
                            donGia = 900000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH015",
                            idSanPham = "SP09",
                            donGia = 1350000m,
                            soluong = 2
                        },
                        new
                        {
                            idDonDat = "DH016",
                            idSanPham = "SP01",
                            donGia = 4500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH017",
                            idSanPham = "SP05",
                            donGia = 3500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH018",
                            idSanPham = "SP14",
                            donGia = 8500000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH019",
                            idSanPham = "SP11",
                            donGia = 1100000m,
                            soluong = 1
                        },
                        new
                        {
                            idDonDat = "DH020",
                            idSanPham = "SP03",
                            donGia = 5200000m,
                            soluong = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WEBNC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("hoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idPhuongXa")
                        .HasColumnType("char(5)");

                    b.Property<string>("soNha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("idPhuongXa");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "USER1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "B3D2E5C5-A1E4-4D71-8B2E-C5D4B3A2C1D2",
                            Email = "Huy91@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Huy91@gmail.com",
                            NormalizedUserName = "Huy91@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAECostYXDzWMxjeRK8BZV9Y2l5j9jgqJ8h65CSvX0UQnI657xBoFczZpIOGj8p8Fm1Q==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A2C1D2A4-F2D5-4E80-9A1F-A6B3A9B2F2A1",
                            TwoFactorEnabled = false,
                            UserName = "Huy91@gmail.com",
                            hoTen = "Phạm Minh Huy",
                            idPhuongXa = "XP001",
                            soNha = "24 Bắc Đẩu"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.ChatMessage", b =>
                {
                    b.Property<int>("idMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMessage"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("idSession")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idMessage");

                    b.HasIndex("idSession");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("WEBNC.Models.ChatSession", b =>
                {
                    b.Property<int>("idSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSession"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idSession");

                    b.HasIndex("userId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("WEBNC.Models.ChiTietGioHang", b =>
                {
                    b.Property<string>("idChiTietGioHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("idNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("idSanPham")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<int>("soLuongTrongGio")
                        .HasColumnType("int");

                    b.HasKey("idChiTietGioHang");

                    b.HasIndex("idNguoiDung");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietGioHang");

                    b.HasData(
                        new
                        {
                            idChiTietGioHang = "GH001",
                            idNguoiDung = "USER1",
                            idSanPham = "SP01",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH002",
                            idNguoiDung = "USER1",
                            idSanPham = "SP08",
                            soLuongTrongGio = 2
                        },
                        new
                        {
                            idChiTietGioHang = "GH003",
                            idNguoiDung = "USER1",
                            idSanPham = "SP03",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH004",
                            idNguoiDung = "USER1",
                            idSanPham = "SP05",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH005",
                            idNguoiDung = "USER1",
                            idSanPham = "SP14",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH006",
                            idNguoiDung = "USER1",
                            idSanPham = "SP19",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH007",
                            idNguoiDung = "USER1",
                            idSanPham = "SP11",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH008",
                            idNguoiDung = "USER1",
                            idSanPham = "SP02",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH009",
                            idNguoiDung = "USER1",
                            idSanPham = "SP22",
                            soLuongTrongGio = 1
                        },
                        new
                        {
                            idChiTietGioHang = "GH010",
                            idNguoiDung = "USER1",
                            idSanPham = "SP16",
                            soLuongTrongGio = 1
                        });
                });

            modelBuilder.Entity("WEBNC.Models.CongTy", b =>
                {
                    b.Property<string>("idCongTy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCongTy");

                    b.ToTable("CongTy");

                    b.HasData(
                        new
                        {
                            idCongTy = "CT01",
                            tenCongTy = "Intel"
                        },
                        new
                        {
                            idCongTy = "CT02",
                            tenCongTy = "AMD"
                        },
                        new
                        {
                            idCongTy = "CT03",
                            tenCongTy = "ASUS"
                        },
                        new
                        {
                            idCongTy = "CT04",
                            tenCongTy = "MSI"
                        },
                        new
                        {
                            idCongTy = "CT05",
                            tenCongTy = "Gigabyte"
                        },
                        new
                        {
                            idCongTy = "CT06",
                            tenCongTy = "Corsair"
                        },
                        new
                        {
                            idCongTy = "CT07",
                            tenCongTy = "Cooler Master"
                        },
                        new
                        {
                            idCongTy = "CT08",
                            tenCongTy = "Kingston"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.DanhGiaSanPham", b =>
                {
                    b.Property<int>("idDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDanhGia"));

                    b.Property<string>("idDonDat")
                        .HasColumnType("char(5)");

                    b.Property<string>("idSanPham")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<DateTime>("ngayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("noiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("soSao")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idDanhGia");

                    b.HasIndex("idDonDat");

                    b.HasIndex("idSanPham");

                    b.HasIndex("userId");

                    b.ToTable("DanhGiaSanPham");
                });

            modelBuilder.Entity("WEBNC.Models.DonDatHang", b =>
                {
                    b.Property<string>("idDonDat")
                        .HasColumnType("char(5)");

                    b.Property<bool>("daThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("idNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ngayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdtGiaoHang")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<string>("soNha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("thanhToan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idDonDat");

                    b.HasIndex("idNguoiDung");

                    b.ToTable("DonDatHang");

                    b.HasData(
                        new
                        {
                            idDonDat = "DH001",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0912345678",
                            soNha = "12 Hàng Bạc",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH002",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0898765432",
                            soNha = "34 Hàng Buồm",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH003",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0913344556",
                            soNha = "56 Bến Nghé",
                            thanhToan = "Chưa thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH004",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0822233345",
                            soNha = "78 Bến Thành",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH005",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0933344455",
                            soNha = "23 An Biên",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH006",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0834455667",
                            soNha = "45 An Dương",
                            thanhToan = "Chưa thanh toán",
                            trangThai = "Đã hủy"
                        },
                        new
                        {
                            idDonDat = "DH007",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0915566778",
                            soNha = "12 An Hòa",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH008",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0891122334",
                            soNha = "34 An Nghiệp",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH009",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0912233445",
                            soNha = "12 Hải Châu I",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH010",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0891122335",
                            soNha = "34 Hải Châu I",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH011",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0919988777",
                            soNha = "56 Hải Châu II",
                            thanhToan = "Chưa thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH012",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0812345679",
                            soNha = "78 Hải Châu II",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH013",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0922233345",
                            soNha = "23 Bình Hiên",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH014",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0834455668",
                            soNha = "45 Bình Hiên",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH015",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0912345567",
                            soNha = "12 An Khê",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH016",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0892345567",
                            soNha = "34 An Khê",
                            thanhToan = "Chưa thanh toán",
                            trangThai = "Đã hủy"
                        },
                        new
                        {
                            idDonDat = "DH017",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0913344557",
                            soNha = "56 Chính Gián",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH018",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0823344557",
                            soNha = "78 Chính Gián",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        },
                        new
                        {
                            idDonDat = "DH019",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0912233445",
                            soNha = "12 Hải Châu I",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đang giao"
                        },
                        new
                        {
                            idDonDat = "DH020",
                            daThanhToan = false,
                            idNguoiDung = "USER1",
                            ngayDat = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayGiaoDuKien = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayThanhToan = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sdtGiaoHang = "0891122335",
                            soNha = "34 Hải Châu I",
                            thanhToan = "Đã thanh toán",
                            trangThai = "Đã giao"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.HinhAnhDanhGia", b =>
                {
                    b.Property<int>("idHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idHinhAnh"));

                    b.Property<int?>("idDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idHinhAnh");

                    b.HasIndex("idDanhGia");

                    b.ToTable("HinhAnhDanhGia");
                });

            modelBuilder.Entity("WEBNC.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("idLoaiSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenLoaiSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLoaiSanPham");

                    b.ToTable("LoaiSanPham");

                    b.HasData(
                        new
                        {
                            idLoaiSanPham = "LSP01",
                            tenLoaiSanPham = "CPU"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP02",
                            tenLoaiSanPham = "Mainboard"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP03",
                            tenLoaiSanPham = "RAM"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP04",
                            tenLoaiSanPham = "Ổ cứng SSD/HDD"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP05",
                            tenLoaiSanPham = "Card đồ họa (GPU)"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP06",
                            tenLoaiSanPham = "Nguồn (PSU)"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP07",
                            tenLoaiSanPham = "Vỏ Case"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP08",
                            tenLoaiSanPham = "Tản nhiệt CPU"
                        },
                        new
                        {
                            idLoaiSanPham = "LSP09",
                            tenLoaiSanPham = "Màn hình"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.SanPham", b =>
                {
                    b.Property<string>("idSanPham")
                        .HasColumnType("char(5)");

                    b.Property<decimal>("gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("idCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("idLoaiSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("imageLienQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongCanDuoi")
                        .HasColumnType("int");

                    b.Property<int>("soLuongHienCon")
                        .HasColumnType("int");

                    b.Property<string>("tenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thongSoSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSanPham");

                    b.HasIndex("idCongTy");

                    b.HasIndex("idLoaiSanPham");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            idSanPham = "SP01",
                            gia = 4300000m,
                            idCongTy = "CT01",
                            idLoaiSanPham = "LSP01",
                            imageLienQuan = "[\"CPU_12400F_1.png\", \"CPU_12400F_2.jpg\", \"CPU_12400F_3.png\", \"CPU_12400F_4.png\"]",
                            imageURL = "CPU_12400F_1.png",
                            moTa = "Intel Core i5-12400F mang lại hiệu năng tuyệt vời cho nhu cầu chơi game và làm việc văn phòng. Sở hữu 6 nhân 12 luồng, tốc độ xử lý cao và tương thích với socket LGA 1700.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 45,
                            tenSanPham = "CPU_12400F_1",
                            thongSoSanPham = "- 6 nhân 12 luồng\r\n- Xung nhịp 2.5GHz (Boost 4.4GHz)\r\n- Socket LGA 1700\r\n- Bộ nhớ đệm 18MB"
                        },
                        new
                        {
                            idSanPham = "SP02",
                            gia = 7500000m,
                            idCongTy = "CT01",
                            idLoaiSanPham = "LSP01",
                            imageLienQuan = "[\"CPU_12700k_1.png\", \"CPU_12700k_2.png\", \"CPU_12700k_3.png\", \"CPU_12700k_4.png\"]",
                            imageURL = "CPU_i7-12700k.jpg",
                            moTa = "CPU Intel Core i7-12700K thuộc dòng Alder Lake mạnh mẽ, hỗ trợ ép xung, 12 nhân 20 luồng, mang đến hiệu năng vượt trội cho cả gaming và công việc sáng tạo.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 20,
                            tenSanPham = "Intel Core i7-12700K",
                            thongSoSanPham = "- 12 nhân 20 luồng\r\n- Xung nhịp 3.6GHz (Boost 5.0GHz)\r\n- Socket LGA 1700\r\n- Hỗ trợ ép xung"
                        },
                        new
                        {
                            idSanPham = "SP03",
                            gia = 4200000m,
                            idCongTy = "CT02",
                            idLoaiSanPham = "LSP01",
                            imageLienQuan = "[\"CPU_5600x_1.png\", \"CPU_5600x_2.jpg\", \"CPU_5600x_3.jpg\", \"CPU_5600x_4.jpg\"]",
                            imageURL = "CPU_Ryzen_5_5600X.jpg",
                            moTa = "AMD Ryzen 5 5600X sử dụng kiến trúc Zen 3 mới, mang lại hiệu năng đơn nhân và đa nhân vượt trội. Lựa chọn tối ưu cho game thủ và dân đồ họa.",
                            soLuongCanDuoi = 15,
                            soLuongHienCon = 50,
                            tenSanPham = "AMD Ryzen 5 5600X",
                            thongSoSanPham = "- 6 nhân 12 luồng\r\n- Kiến trúc Zen 3\r\n- Xung nhịp 3.7GHz (Boost 4.6GHz)\r\n- Socket AM4"
                        },
                        new
                        {
                            idSanPham = "SP04",
                            gia = 8900000m,
                            idCongTy = "CT02",
                            idLoaiSanPham = "LSP01",
                            imageLienQuan = "[\"CPU_7800x3d_1.jpg\", \"CPU_7800x3d_2.jpg\", \"CPU_7800x3d_3.jpg\", \"CPU_7800x3d_4.jpg\"]",
                            imageURL = "CPU_Ryzen_7_5800X3D.jpg",
                            moTa = "Ryzen 7 5800X3D với công nghệ 3D V-Cache độc quyền của AMD giúp tăng hiệu năng game đáng kể, là CPU lý tưởng cho trải nghiệm chơi game cao cấp.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 12,
                            tenSanPham = "AMD Ryzen 7 5800X3D",
                            thongSoSanPham = "- 8 nhân 16 luồng\r\n- Xung nhịp 3.4GHz (Boost 4.5GHz)\r\n- Công nghệ 3D V-Cache\r\n- Socket AM4"
                        },
                        new
                        {
                            idSanPham = "SP05",
                            gia = 4500000m,
                            idCongTy = "CT03",
                            idLoaiSanPham = "LSP02",
                            imageLienQuan = "[\"MAIN_b550f_1.jpg\", \"MAIN_b550f_2.jpg\", \"MAIN_b550f_3.jpg\", \"MAIN_b550f_4.jpg\"]",
                            imageURL = "MAIN_ASUS_ROG_Strix_B550-F.jpg",
                            moTa = "Mainboard ASUS ROG Strix B550-F Gaming hỗ trợ các CPU Ryzen thế hệ mới, trang bị tản nhiệt VRM cao cấp và nhiều cổng kết nối hiện đại như PCIe 4.0 và USB 3.2 Gen2.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 35,
                            tenSanPham = "ASUS ROG Strix B550-F",
                            thongSoSanPham = "- Chipset B550\r\n- Socket AM4\r\n- Hỗ trợ PCIe 4.0\r\n- 4 khe RAM DDR4 (Tối đa 128GB)"
                        },
                        new
                        {
                            idSanPham = "SP06",
                            gia = 4900000m,
                            idCongTy = "CT04",
                            idLoaiSanPham = "LSP02",
                            imageLienQuan = "[\"MAIN_B660_1.png\", \"MAIN_B660_2.jpg\", \"MAIN_B660_3.jpg\", \"MAIN_B660_4.jpg\"]",
                            imageURL = "MAIN_B660_1.png",
                            moTa = "MSI B660 Tomahawk mang thiết kế mạnh mẽ, hỗ trợ CPU Intel thế hệ 12, có khe PCIe Gen4 và cổng LAN 2.5G, phù hợp cho cấu hình tầm trung và cao cấp.",
                            soLuongCanDuoi = 15,
                            soLuongHienCon = 40,
                            tenSanPham = "MSI B660 Tomahawk",
                            thongSoSanPham = "- Chipset B660\r\n- Socket LGA 1700\r\n- Hỗ trợ PCIe Gen4\r\n- LAN 2.5G / USB 3.2 Gen2"
                        },
                        new
                        {
                            idSanPham = "SP07",
                            gia = 5600000m,
                            idCongTy = "CT05",
                            idLoaiSanPham = "LSP02",
                            imageLienQuan = "[\"MAIN_z690_1.jpg\", \"MAIN_z690_2.jpg\", \"MAIN_z690_3.jpg\", \"MAIN_z690_4.jpg\"]",
                            imageURL = "MAIN_Gigabyte_Z690_Aorus_Elite.png",
                            moTa = "Bo mạch chủ Gigabyte Z690 Aorus Elite hỗ trợ DDR5, nhiều cổng M.2 tốc độ cao và thiết kế tản nhiệt mạnh mẽ, đảm bảo hoạt động ổn định trong thời gian dài.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 18,
                            tenSanPham = "Gigabyte Z690 Aorus Elite",
                            thongSoSanPham = "- Chipset Z690\r\n- Socket LGA 1700\r\n- Hỗ trợ DDR5 / PCIe 5.0\r\n- 3 khe M.2 NVMe"
                        },
                        new
                        {
                            idSanPham = "SP08",
                            gia = 1100000m,
                            idCongTy = "CT08",
                            idLoaiSanPham = "LSP03",
                            imageLienQuan = "[\"RAM_fury_1.jpg\", \"RAM_fury_2.jpg\", \"RAM_fury_3.jpg\", \"RAM_fury_4.jpg\"]",
                            imageURL = "RAM_Kingston_Fury_Beast_16GB_DDR4_3200.jpg",
                            moTa = "RAM Kingston Fury Beast 16GB DDR4 3200 mang lại hiệu năng ổn định, khả năng tương thích cao và thiết kế mạnh mẽ, lý tưởng cho các game thủ và dân văn phòng.",
                            soLuongCanDuoi = 20,
                            soLuongHienCon = 60,
                            tenSanPham = "Kingston Fury Beast 16GB DDR4 3200",
                            thongSoSanPham = "- Dung lượng 16GB (1x16GB)\r\n- Bus 3200MHz\r\n- Loại DDR4\r\n- Điện áp 1.35V"
                        },
                        new
                        {
                            idSanPham = "SP09",
                            gia = 1150000m,
                            idCongTy = "CT06",
                            idLoaiSanPham = "LSP03",
                            imageLienQuan = "[\"RAM_corsairN_1.jpg\", \"RAM_corsairN_2.jpg\", \"RAM_corsairN_3.jpg\", \"RAM_corsairN_4.jpg\"]",
                            imageURL = "RAM_corsairN_1.jpg",
                            moTa = "Corsair Vengeance LPX 16GB DDR4 3600 được thiết kế để ép xung tối đa, tản nhiệt nhôm cao cấp, đảm bảo tốc độ và độ bền vượt trội cho hệ thống.",
                            soLuongCanDuoi = 15,
                            soLuongHienCon = 55,
                            tenSanPham = "Corsair Vengeance LPX 16GB DDR4 3600",
                            thongSoSanPham = "- Dung lượng 16GB (2x8GB)\r\n- Bus 3600MHz\r\n- Loại DDR4\r\n- Tản nhiệt nhôm cao cấp"
                        },
                        new
                        {
                            idSanPham = "SP10",
                            gia = 3200000m,
                            idCongTy = "CT06",
                            idLoaiSanPham = "LSP03",
                            imageLienQuan = "[\"RAM_corsair_1.png\", \"RAM_corsair_2.png\", \"RAM_corsair_3.png\", \"RAM_corsair_4.png\"]",
                            imageURL = "RAM_corsair_3.png",
                            moTa = "Dòng RAM DDR5 cao cấp với dải đèn RGB rực rỡ, tốc độ siêu nhanh 5600MHz, mang lại hiệu năng đỉnh cao cho các dàn máy chơi game hiện đại.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 25,
                            tenSanPham = "Corsair Vengeance RGB 32GB DDR5 5600",
                            thongSoSanPham = "- Dung lượng 32GB (2x16GB)\r\n- Bus 5600MHz\r\n- Loại DDR5\r\n- RGB tùy chỉnh"
                        },
                        new
                        {
                            idSanPham = "SP11",
                            gia = 1600000m,
                            idCongTy = "CT08",
                            idLoaiSanPham = "LSP04",
                            imageLienQuan = "[\"SSD_KT1T_1.jpg\", \"SSD_KT1T_2.jpg\", \"SSD_KT1T_3.png\", \"SSD_KT1T_4.jpeg\"]",
                            imageURL = "SSD_KT1T_1.jpg",
                            moTa = "SSD Kingston NV2 1TB sử dụng chuẩn NVMe Gen4 tốc độ cao, mang đến khả năng khởi động và tải ứng dụng cực nhanh, tiết kiệm điện năng và bền bỉ.",
                            soLuongCanDuoi = 25,
                            soLuongHienCon = 70,
                            tenSanPham = "Kingston NV2 1TB NVMe SSD",
                            thongSoSanPham = "- Dung lượng 1TB\r\n- Chuẩn NVMe PCIe 4.0\r\n- Đọc: 3500MB/s, Ghi: 2100MB/s\r\n- Hệ số hình dạng M.2 2280"
                        },
                        new
                        {
                            idSanPham = "SP12",
                            gia = 2500000m,
                            idCongTy = "CT06",
                            idLoaiSanPham = "LSP04",
                            imageLienQuan = "[\"SSD_CS1T_1.jpg\", \"SSD_CS1T_2.jpg\", \"SSD_CS1T_3.jpg\", \"SSD_CS1T_4.jpg\"]",
                            imageURL = "SSD_Corsair_MP600_1TB_NVMe_SSD.jpg",
                            moTa = "Corsair MP600 1TB là dòng SSD PCIe Gen4 hiệu suất cực cao, đạt tốc độ đọc ghi lên đến 4950MB/s, phù hợp cho dân chơi PC hiệu năng.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 30,
                            tenSanPham = "Corsair MP600 1TB NVMe SSD",
                            thongSoSanPham = "- Dung lượng 1TB\r\n- Chuẩn NVMe PCIe 4.0 x4\r\n- Tốc độ đọc: 4950MB/s, ghi: 4250MB/s\r\n- Tản nhiệt nhôm"
                        },
                        new
                        {
                            idSanPham = "SP13",
                            gia = 1400000m,
                            idCongTy = "CT05",
                            idLoaiSanPham = "LSP04",
                            imageLienQuan = "[\"HDD_WD2T_1.jpg\", \"HDD_WD2T_2.jpg\", \"HDD_WD2T_3.jpeg\", \"HDD_WD2T_4.jpg\"]",
                            imageURL = "HDD_WD2T_1.jpg",
                            moTa = "Ổ cứng HDD Gigabyte 2TB tốc độ 7200 vòng/phút, cung cấp dung lượng lưu trữ lớn, độ bền cao, thích hợp cho việc lưu trữ dữ liệu lâu dài.",
                            soLuongCanDuoi = 15,
                            soLuongHienCon = 45,
                            tenSanPham = "Gigabyte 2TB HDD 7200rpm",
                            thongSoSanPham = "- Dung lượng 2TB\r\n- Loại HDD 3.5 inch\r\n- Tốc độ quay 7200rpm\r\n- Cache 64MB"
                        },
                        new
                        {
                            idSanPham = "SP14",
                            gia = 8700000m,
                            idCongTy = "CT04",
                            idLoaiSanPham = "LSP05",
                            imageLienQuan = "[\"VGA_30602x_1.jpg\", \"VGA_30602x_2.jpg\", \"VGA_30602x_3.jpg\", \"VGA_30602x_4.jpg\"]",
                            imageURL = "VGA_MSI_RTX_3060_Ventus_2X_12GB.jpg",
                            moTa = "MSI RTX 3060 Ventus 2X trang bị 12GB VRAM GDDR6, mang lại khả năng xử lý đồ họa ấn tượng, chơi tốt các tựa game AAA ở độ phân giải Full HD và 2K.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 28,
                            tenSanPham = "MSI RTX 3060 Ventus 2X 12GB",
                            thongSoSanPham = "- GPU NVIDIA RTX 3060\r\n- VRAM 12GB GDDR6\r\n- Giao tiếp PCIe 4.0\r\n- Nguồn khuyến nghị 550W"
                        },
                        new
                        {
                            idSanPham = "SP15",
                            gia = 11300000m,
                            idCongTy = "CT05",
                            idLoaiSanPham = "LSP05",
                            imageLienQuan = "[\"VGA_30703x_1.jpg\", \"VGA_30703x_2.jpg\", \"VGA_30703x_3.jpg\", \"VGA_30703x_4.jpg\"]",
                            imageURL = "VGA_Gigabyte_RTX_3070_Gaming_OC_8GB.jpg",
                            moTa = "Gigabyte RTX 3070 Gaming OC là GPU mạnh mẽ với hiệu năng cao, hỗ trợ Ray Tracing, DLSS, mang lại trải nghiệm gaming đỉnh cao.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 18,
                            tenSanPham = "Gigabyte RTX 3070 Gaming OC 8GB",
                            thongSoSanPham = "- GPU NVIDIA RTX 3070\r\n- VRAM 8GB GDDR6\r\n- Ray Tracing / DLSS 2.0\r\n- Nguồn khuyến nghị 650W"
                        },
                        new
                        {
                            idSanPham = "SP16",
                            gia = 16900000m,
                            idCongTy = "CT03",
                            idLoaiSanPham = "LSP05",
                            imageLienQuan = "[\"VGA_30803x_1.jpg\", \"VGA_30803x_2.jpg\", \"VGA_30803x_3.jpg\", \"VGA_30803x_4.jpg\"]",
                            imageURL = "VGA_ASUS_TUF_Gaming_RTX_3080_10GB.jpg",
                            moTa = "ASUS TUF Gaming RTX 3080 10GB có hiệu năng cực mạnh cho gaming 4K, trang bị hệ thống tản nhiệt tối ưu và thiết kế bền bỉ đạt chuẩn quân đội.",
                            soLuongCanDuoi = 3,
                            soLuongHienCon = 8,
                            tenSanPham = "ASUS TUF Gaming RTX 3080 10GB",
                            thongSoSanPham = "- GPU NVIDIA RTX 3080\r\n- VRAM 10GB GDDR6X\r\n- Tản nhiệt 3 quạt TUF\r\n- Nguồn khuyến nghị 750W"
                        },
                        new
                        {
                            idSanPham = "SP17",
                            gia = 1300000m,
                            idCongTy = "CT07",
                            idLoaiSanPham = "LSP06",
                            imageLienQuan = "[\"PSU_650w_1.png\", \"PSU_650w_2.png\", \"PSU_650w_3.png\", \"PSU_650w_4.png\"]",
                            imageURL = "PSU_650w_3.png",
                            moTa = "Cooler Master MWE 650W đạt chứng nhận 80+ Bronze, hiệu suất ổn định, hoạt động êm ái và an toàn cho toàn bộ hệ thống.",
                            soLuongCanDuoi = 15,
                            soLuongHienCon = 40,
                            tenSanPham = "Cooler Master MWE 650W 80+ Bronze",
                            thongSoSanPham = "- Công suất 650W\r\n- Chứng nhận 80+ Bronze\r\n- Quạt 120mm yên tĩnh\r\n- Bảo vệ OVP / OCP / SCP"
                        },
                        new
                        {
                            idSanPham = "SP18",
                            gia = 2600000m,
                            idCongTy = "CT06",
                            idLoaiSanPham = "LSP06",
                            imageLienQuan = "[\"PSU_Corsair_RM750x_750W_80+_Gold.jpg\", \"PSU_650w_2.png\", \"PSU_Corsair_RM750x_750W_80+_Gold.jpg\", \"PSU_750w_4.png\"]",
                            imageURL = "PSU_Corsair_RM750x_750W_80+_Gold.jpg",
                            moTa = "Corsair RM750x 750W cung cấp công suất ổn định, hiệu suất cao 80+ Gold, dây cáp bọc lưới mềm, hoạt động yên tĩnh với quạt Zero RPM.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 20,
                            tenSanPham = "Corsair RM750x 750W 80+ Gold",
                            thongSoSanPham = "- Công suất 750W\r\n- Chứng nhận 80+ Gold\r\n- Dây cáp rời mềm\r\n- Quạt Zero RPM"
                        },
                        new
                        {
                            idSanPham = "SP19",
                            gia = 1800000m,
                            idCongTy = "CT07",
                            idLoaiSanPham = "LSP07",
                            imageLienQuan = "[\"CASE_td500_1.jpg\", \"CASE_td500_2.jpg\", \"CASE_td500_3.jpg\", \"CASE_td500_4.jpg\"]",
                            imageURL = "CASE_Cooler_Master_MasterBox_TD500.jpg",
                            moTa = "Thiết kế góc cạnh ấn tượng, mặt kính cường lực và hệ thống đèn RGB nổi bật, MasterBox TD500 mang lại vẻ đẹp hiện đại cho dàn PC.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 30,
                            tenSanPham = "Cooler Master MasterBox TD500",
                            thongSoSanPham = "- Hỗ trợ main ATX / mATX / ITX\r\n- 3 quạt RGB đi kèm\r\n- Mặt kính cường lực\r\n- Kích thước: Mid Tower"
                        },
                        new
                        {
                            idSanPham = "SP20",
                            gia = 2100000m,
                            idCongTy = "CT03",
                            idLoaiSanPham = "LSP07",
                            imageLienQuan = "[\"CASE_tuf_1.jpg\", \"CASE_tuf_2.jpg\", \"CASE_tuf_3.jpg\", \"CASE_tuf_4.jpg\"]",
                            imageURL = "CASE_tuf_1.jpg",
                            moTa = "ASUS TUF Gaming GT301 có thiết kế bền bỉ, hỗ trợ nhiều quạt làm mát, dễ dàng lắp đặt và phù hợp với các bo mạch chủ ATX, Micro-ATX.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 25,
                            tenSanPham = "ASUS TUF Gaming GT301",
                            thongSoSanPham = "- Hỗ trợ main ATX / Micro-ATX\r\n- Lưới tản nhiệt mặt trước\r\n- Kính cường lực bên hông\r\n- 3 quạt LED TUF kèm theo"
                        },
                        new
                        {
                            idSanPham = "SP21",
                            gia = 950000m,
                            idCongTy = "CT07",
                            idLoaiSanPham = "LSP08",
                            imageLienQuan = "[\"TNHIET_212_1.png\", \"TNHIET_212_2.png\", \"TNHIET_212_3.png\", \"TNHIET_212_4.png\"]",
                            imageURL = "TNHIET_Cooler_Master_Hyper_212_Black_Edition.jpg",
                            moTa = "Cooler Master Hyper 212 Black Edition là tản khí huyền thoại với khả năng làm mát hiệu quả, hoạt động êm ái, phù hợp cho các CPU tầm trung.",
                            soLuongCanDuoi = 20,
                            soLuongHienCon = 50,
                            tenSanPham = "Cooler Master Hyper 212 Black Edition",
                            thongSoSanPham = "- Loại tản khí\r\n- Quạt 120mm PWM\r\n- Độ ồn thấp\r\n- Hỗ trợ Intel / AMD"
                        },
                        new
                        {
                            idSanPham = "SP22",
                            gia = 3200000m,
                            idCongTy = "CT06",
                            idLoaiSanPham = "LSP08",
                            imageLienQuan = "[\"TNHIET_h100i_1.jpg\", \"TNHIET_h100i_2.jpg\", \"TNHIET_h100i_3.jpg\", \"TNHIET_h100i_4.jpg\"]",
                            imageURL = "TNHIET_Corsair_iCUE_H100i_Elite_Liquid_Cooler.jpg",
                            moTa = "Tản nhiệt nước Corsair iCUE H100i Elite với đèn RGB tùy chỉnh, hiệu suất làm mát cao, điều khiển thông minh qua phần mềm iCUE.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 20,
                            tenSanPham = "Corsair iCUE H100i Elite Liquid Cooler",
                            thongSoSanPham = "- Loại tản nước AIO 240mm\r\n- 2 quạt 120mm RGB\r\n- Điều khiển qua phần mềm iCUE\r\n- Hỗ trợ Intel & AMD"
                        },
                        new
                        {
                            idSanPham = "SP23",
                            gia = 5600000m,
                            idCongTy = "CT03",
                            idLoaiSanPham = "LSP09",
                            imageLienQuan = "[\"MHINH_TUF_1.jpg\", \"MHINH_TUF_2.jpg\", \"MHINH_TUF_3.jpg\", \"MHINH_TUF_4.jpg\"]",
                            imageURL = "MHinh_MASUS_TUF_Gaming_VG259QM.jpg",
                            moTa = "Màn hình ASUS TUF VG259QM với tần số quét 280Hz và thời gian phản hồi 1ms, hiển thị mượt mà cho các game eSports.",
                            soLuongCanDuoi = 5,
                            soLuongHienCon = 15,
                            tenSanPham = "ASUS TUF Gaming VG259QM 24.5 inch, FHD, IPS, 280Hz, 1ms",
                            thongSoSanPham = "- Kích thước 24.5 inch\r\n- Tấm nền IPS\r\n- Tần số quét 280Hz\r\n- Thời gian phản hồi 1ms"
                        },
                        new
                        {
                            idSanPham = "SP24",
                            gia = 4700000m,
                            idCongTy = "CT04",
                            idLoaiSanPham = "LSP09",
                            imageLienQuan = "[\"MHINH_MSI_1.png\", \"MHINH_MSI_2.png\", \"MHINH_MSI_3.png\", \"MHINH_MSI_4.png\"]",
                            imageURL = "MHinh_MSI_G2712FDE.jpg",
                            moTa = "MSI G2712FDE mang đến trải nghiệm hình ảnh sống động, tấm nền IPS cao cấp và tần số quét 180Hz cực nhanh.",
                            soLuongCanDuoi = 10,
                            soLuongHienCon = 35,
                            tenSanPham = "MSI G2712FDE (27 inch, Full HD, 180Hz, Rapid IPS, 1ms, Black)",
                            thongSoSanPham = "- Kích thước 27 inch\r\n- Độ phân giải Full HD\r\n- Tần số quét 180Hz\r\n- Tấm nền Rapid IPS"
                        },
                        new
                        {
                            idSanPham = "SP25",
                            gia = 3600000m,
                            idCongTy = "CT05",
                            idLoaiSanPham = "LSP09",
                            imageLienQuan = "[\"MHINH_GGB_1.png\", \"MHINH_GGB_2.png\", \"MHINH_GGB_3.png\", \"MHINH_GGB_4.png\"]",
                            imageURL = "MHinh_Gigabyte_G24F2.jpg",
                            moTa = "Màn hình Gigabyte G24F2 có thiết kế mỏng nhẹ, tần số quét 165Hz, hỗ trợ ép xung 180Hz, rất lý tưởng cho game thủ FPS.",
                            soLuongCanDuoi = 15,
                            soLuongHienCon = 40,
                            tenSanPham = "Gigabyte G24F2 (23.8inch, FHD, IPS, 165Hz, 180Hz(OC), 1ms)",
                            thongSoSanPham = "- Kích thước 23.8 inch\r\n- Độ phân giải Full HD\r\n- Tần số quét 165Hz (OC 180Hz)\r\n- Tấm nền IPS / Thời gian phản hồi 1ms"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.ThanhToan", b =>
                {
                    b.Property<int>("idThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThanhToan"));

                    b.Property<bool>("daThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("idDonDat")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<string>("maGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("phuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("soTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idThanhToan");

                    b.HasIndex("idDonDat");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("WEBNC.Models.ThongBao", b =>
                {
                    b.Property<int>("idThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThongBao"));

                    b.Property<bool>("daDoc")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("noiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("tieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idThongBao");

                    b.HasIndex("userId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("WEBNC.Models.Tinh", b =>
                {
                    b.Property<string>("idTinh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTinh");

                    b.ToTable("Tinh");

                    b.HasData(
                        new
                        {
                            idTinh = "T001",
                            tenTinh = "Hà Nội"
                        },
                        new
                        {
                            idTinh = "T002",
                            tenTinh = "TP Hồ Chí Minh"
                        },
                        new
                        {
                            idTinh = "T003",
                            tenTinh = "Đà Nẵng"
                        },
                        new
                        {
                            idTinh = "T004",
                            tenTinh = "Hải Phòng"
                        },
                        new
                        {
                            idTinh = "T005",
                            tenTinh = "Cần Thơ"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.XaPhuong", b =>
                {
                    b.Property<string>("idXaPhuong")
                        .HasColumnType("char(5)");

                    b.Property<string>("idTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenXaPhuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idXaPhuong");

                    b.HasIndex("idTinh");

                    b.ToTable("XaPhuong");

                    b.HasData(
                        new
                        {
                            idXaPhuong = "XP001",
                            idTinh = "T001",
                            tenXaPhuong = "Phường Hàng Bạc"
                        },
                        new
                        {
                            idXaPhuong = "XP002",
                            idTinh = "T001",
                            tenXaPhuong = "Phường Hàng Buồm"
                        },
                        new
                        {
                            idXaPhuong = "XP003",
                            idTinh = "T001",
                            tenXaPhuong = "Phường Tràng Tiền"
                        },
                        new
                        {
                            idXaPhuong = "XP004",
                            idTinh = "T001",
                            tenXaPhuong = "Phường Ngọc Hà"
                        },
                        new
                        {
                            idXaPhuong = "XP005",
                            idTinh = "T001",
                            tenXaPhuong = "Phường Kim Mã"
                        },
                        new
                        {
                            idXaPhuong = "XP006",
                            idTinh = "T001",
                            tenXaPhuong = "Phường Điện Biên"
                        },
                        new
                        {
                            idXaPhuong = "XP007",
                            idTinh = "T002",
                            tenXaPhuong = "Phường Bến Nghé"
                        },
                        new
                        {
                            idXaPhuong = "XP008",
                            idTinh = "T002",
                            tenXaPhuong = "Phường Bến Thành"
                        },
                        new
                        {
                            idXaPhuong = "XP009",
                            idTinh = "T002",
                            tenXaPhuong = "Phường Nguyễn Thái Bình"
                        },
                        new
                        {
                            idXaPhuong = "XP010",
                            idTinh = "T002",
                            tenXaPhuong = "Phường 1"
                        },
                        new
                        {
                            idXaPhuong = "XP011",
                            idTinh = "T002",
                            tenXaPhuong = "Phường 2"
                        },
                        new
                        {
                            idXaPhuong = "XP012",
                            idTinh = "T002",
                            tenXaPhuong = "Phường 3"
                        },
                        new
                        {
                            idXaPhuong = "XP013",
                            idTinh = "T003",
                            tenXaPhuong = "Phường Hải Châu I"
                        },
                        new
                        {
                            idXaPhuong = "XP014",
                            idTinh = "T003",
                            tenXaPhuong = "Phường Hải Châu II"
                        },
                        new
                        {
                            idXaPhuong = "XP015",
                            idTinh = "T003",
                            tenXaPhuong = "Phường Bình Hiên"
                        },
                        new
                        {
                            idXaPhuong = "XP016",
                            idTinh = "T003",
                            tenXaPhuong = "Phường An Khê"
                        },
                        new
                        {
                            idXaPhuong = "XP017",
                            idTinh = "T003",
                            tenXaPhuong = "Phường Chính Gián"
                        },
                        new
                        {
                            idXaPhuong = "XP018",
                            idTinh = "T003",
                            tenXaPhuong = "Phường Tam Thuận"
                        },
                        new
                        {
                            idXaPhuong = "XP019",
                            idTinh = "T004",
                            tenXaPhuong = "Phường An Biên"
                        },
                        new
                        {
                            idXaPhuong = "XP020",
                            idTinh = "T004",
                            tenXaPhuong = "Phường An Dương"
                        },
                        new
                        {
                            idXaPhuong = "XP021",
                            idTinh = "T004",
                            tenXaPhuong = "Phường Dư Hàng"
                        },
                        new
                        {
                            idXaPhuong = "XP022",
                            idTinh = "T004",
                            tenXaPhuong = "Phường Hoàng Văn Thụ"
                        },
                        new
                        {
                            idXaPhuong = "XP023",
                            idTinh = "T004",
                            tenXaPhuong = "Phường Hạ Lý"
                        },
                        new
                        {
                            idXaPhuong = "XP024",
                            idTinh = "T004",
                            tenXaPhuong = "Phường Quán Toan"
                        },
                        new
                        {
                            idXaPhuong = "XP025",
                            idTinh = "T005",
                            tenXaPhuong = "Phường An Hòa"
                        },
                        new
                        {
                            idXaPhuong = "XP026",
                            idTinh = "T005",
                            tenXaPhuong = "Phường An Nghiệp"
                        },
                        new
                        {
                            idXaPhuong = "XP027",
                            idTinh = "T005",
                            tenXaPhuong = "Phường Tân An"
                        },
                        new
                        {
                            idXaPhuong = "XP028",
                            idTinh = "T005",
                            tenXaPhuong = "Phường An Thới"
                        },
                        new
                        {
                            idXaPhuong = "XP029",
                            idTinh = "T005",
                            tenXaPhuong = "Phường Bình Thủy"
                        },
                        new
                        {
                            idXaPhuong = "XP030",
                            idTinh = "T005",
                            tenXaPhuong = "Phường Trà An"
                        });
                });

            modelBuilder.Entity("WEBNC.Models.YeuCauDoiTra", b =>
                {
                    b.Property<int>("idYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idYeuCau"));

                    b.Property<string>("idDonDat")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<string>("lyDo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idYeuCau");

                    b.HasIndex("idDonDat");

                    b.HasIndex("userId");

                    b.ToTable("YeuCauDoiTra");
                });

            modelBuilder.Entity("ChiTietDonHang", b =>
                {
                    b.HasOne("WEBNC.Models.DonDatHang", "DonDatHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("idDonDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBNC.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBNC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WEBNC.Models.ApplicationUser", b =>
                {
                    b.HasOne("WEBNC.Models.XaPhuong", "xaPhuong")
                        .WithMany()
                        .HasForeignKey("idPhuongXa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("xaPhuong");
                });

            modelBuilder.Entity("WEBNC.Models.ChatMessage", b =>
                {
                    b.HasOne("WEBNC.Models.ChatSession", "session")
                        .WithMany()
                        .HasForeignKey("idSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("session");
                });

            modelBuilder.Entity("WEBNC.Models.ChatSession", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WEBNC.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("idNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBNC.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("user");
                });

            modelBuilder.Entity("WEBNC.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("WEBNC.Models.DonDatHang", "DonDatHang")
                        .WithMany()
                        .HasForeignKey("idDonDat");

                    b.HasOne("WEBNC.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBNC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("SanPham");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WEBNC.Models.DonDatHang", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", "nguoiDung")
                        .WithMany("DonDatHangs")
                        .HasForeignKey("idNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("WEBNC.Models.HinhAnhDanhGia", b =>
                {
                    b.HasOne("WEBNC.Models.DanhGiaSanPham", "DanhGiaSanPham")
                        .WithMany("HinhAnhDanhGias")
                        .HasForeignKey("idDanhGia");

                    b.Navigation("DanhGiaSanPham");
                });

            modelBuilder.Entity("WEBNC.Models.SanPham", b =>
                {
                    b.HasOne("WEBNC.Models.CongTy", "congTy")
                        .WithMany("SanPhams")
                        .HasForeignKey("idCongTy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBNC.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("idLoaiSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");

                    b.Navigation("congTy");
                });

            modelBuilder.Entity("WEBNC.Models.ThanhToan", b =>
                {
                    b.HasOne("WEBNC.Models.DonDatHang", "DonDatHang")
                        .WithMany()
                        .HasForeignKey("idDonDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatHang");
                });

            modelBuilder.Entity("WEBNC.Models.ThongBao", b =>
                {
                    b.HasOne("WEBNC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WEBNC.Models.XaPhuong", b =>
                {
                    b.HasOne("WEBNC.Models.Tinh", "tinh")
                        .WithMany("xaPhuongs")
                        .HasForeignKey("idTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tinh");
                });

            modelBuilder.Entity("WEBNC.Models.YeuCauDoiTra", b =>
                {
                    b.HasOne("WEBNC.Models.DonDatHang", "DonDatHang")
                        .WithMany()
                        .HasForeignKey("idDonDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBNC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WEBNC.Models.ApplicationUser", b =>
                {
                    b.Navigation("DonDatHangs");
                });

            modelBuilder.Entity("WEBNC.Models.CongTy", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WEBNC.Models.DanhGiaSanPham", b =>
                {
                    b.Navigation("HinhAnhDanhGias");
                });

            modelBuilder.Entity("WEBNC.Models.DonDatHang", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("WEBNC.Models.Tinh", b =>
                {
                    b.Navigation("xaPhuongs");
                });
#pragma warning restore 612, 618
        }
    }
}
